### ISSUE TITLE
Applied Energistics not in the mods folder

### ISSUE THREAD

**Issue by king4q** [MyM-ModpackTeam/MyM-Skies#13]
AE2 is not in the currently listed mods folder of the mods currently gonna be in the pack but is in the modlist.md

**Comment by Aiidoneus** [comment]
Odd. I will fix that. Thank you for letting me know.

**Comment by Aiidoneus** [comment]
It is there. Just github orders the mods alphabetical and by capitalization
https://github.com/MyM-ModpackTeam/MyM-Skies/blob/master/src/mods/appliedenergistics2-rv3-beta-6.jar
