### ISSUE TITLE
Tardis and Dalek Mods

### ISSUE THREAD

**Issue by king4q** [MyM-ModpackTeam/MyM-Skies#14]
similar to the tardis in galatic science i loved it but it was so far end game there wasnt much reason to make it other than for the quest so if it is added i would like it to not be end-game but to be a earlier on version of it or if it is end game for the players to have a reason to use it and play afterwards

**Comment by Aiidoneus** [comment]
I am going to go ahead and say no to this. These mods are not server friendly and very hard to manage. 
Sorry.
