### ISSUE TITLE
Suggestion: Better Builder's Wands

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/MyM-Skies#18]
https://minecraft.curseforge.com/projects/better-builders-wands

Either that or give the Wand from ExU are very early game recipe.

**Comment by Kaymax99** [comment]
I support this

**Comment by Aiidoneus** [comment]
@wyndman What do you think?

**Comment by Aiidoneus** [comment]
Went ahead and added this. Will be in next version.
