### ISSUE TITLE
Suggestion: Mekanism, Mekanism Generators, Mekanism Tools

### ISSUE THREAD

**Issue by Kaymax99** [MyM-ModpackTeam/MyM-Skies#8]
Wanted to suggest Mekanism and its addons (Mekanism Generators and Mekanism Tools)

**Comment by Aiidoneus** [comment]
If I were to add this, this would be going into Hard-Mode and not Normal-Mode

**Comment by Kaymax99** [comment]
I understand, thanks!

**Comment by Kaymax99** [comment]
My bad, misunderstood

**Comment by Aiidoneus** [comment]
Added to next version!
